"use client";
import React from "react";

export default function ShippingPolicy() {
  return (
    <main className="bg-background min-h-screen text-foreground py-40 md:py-60 px-6">
       <div className="max-w-[800px] mx-auto flex flex-col gap-20">
          <div className="flex flex-col gap-6">
             <span className="text-[10px] font-bold tracking-[0.5em] uppercase text-foreground/20">Logistics Architecture // 0.1</span>
             <h1 className="text-5xl md:text-8xl font-bold uppercase tracking-tighter">Shipping<br/>Nodes</h1>
          </div>

          <div className="flex flex-col gap-16 text-[10px] md:text-xs font-bold uppercase tracking-[0.2em] leading-loose text-foreground/60">
             <section className="flex flex-col gap-6">
                <h3 className="text-foreground text-sm tracking-widest">1. GLOBAL DEPLOYMENT</h3>
                <p>DENIMX OPERATES FROM GROUND ZERO (TOKYO). WE SHIP TO EVERY ACTIVE GLOBAL COORDINATE. ALL SHIPMENTS ARE INSURED AND TRACKED THROUGH OUR CENTRAL COMMAND CENTER.</p>
             </section>

             <section className="flex flex-col gap-6">
                <h3 className="text-foreground text-sm tracking-widest">2. TEMPORAL ESTIMATES</h3>
                <p>JAPAN DOMESTIC: 2-3 PROTOCOL DAYS.<br/>INTERNATIONAL SYSTEMS: 7-14 PROTOCOL DAYS DEPENDING ON REGIONAL CLEARANCE NODES.</p>
             </section>

             <section className="flex flex-col gap-6">
                <h3 className="text-foreground text-sm tracking-widest">3. DUTY & EXCISE</h3>
                <p>RECIPIENTS ARE RESPONSIBLE FOR ANY LOCAL IMPORT DUTIES OR TAXES GENERATED BY THEIR REGIONAL GOVERNMENTS.</p>
             </section>
          </div>
       </div>
    </main>
  );
}
